<div class="title-page">
     <h2><?= $this->msg; ?></h2>
    <? if($this->empty!=null):?>
        <h2><?= $this->empty; ?></h2>
    <? endif ?>
</div>
<? if($this->centri!=null):?>
<div style="width: 1005px; margin: auto">
    <div class="tab topRow" style="width: 1005px">
        <div class="tab-element rightBorder" style="width: 200px; float:left;height: 50px; text-align: center">Nome</div>
        <div class="tab-element rightBorder" style="width: 350px;float:left; height: 50px; text-align: center">Indirizzo</div>
        <div class="tab-element rightBorder" style="width: 250px; height: 50px; float:left; text-align: center">Mail</div>
        <div class="tab-element rightBorder" style="width: 100px; height: 50px; float:left; text-align: center">Modifica</div>
        <div class="tab-element" style="width: 100px; height: 50px; float:left; text-align: center">Elimina</div>
    </div>
    <? foreach($this->centri as $item): ?>
        <a href="#" class="tab noRound admin-centro" value="<?= $item['id_centro']; ?>" style="width: 1005px">
            <div class="tab-element rightBorder" style="width: 200px; float:left;height: 50px; text-align: center">
                <?= $item['nome']; ?>
            </div>

            <div class="tab-element rightBorder" style="width: 350px;float:left; height: 50px; text-align: center">
                <?= $item['indirizzo']; ?>
            </div>

            <div class="tab-element rightBorder" style="width: 250px; height: 50px; float:left; text-align: center">
                <?= $item['mail']; ?>
            </div>

            <div class="tab-element rightBorder" style="width: 100px; height: 50px; float:left; text-align: center"><i class="fa fa-pencil"></i></div>

            <div class="tab-element" style="width: 100px; height: 50px; float:left; text-align: center"><i class="fa fa-trash"></i></div>
        </a>
    <? endforeach; ?>
</div>
<? endif ?>
