<div class="title-page">
    <h2><?= $this->msg; ?></h2>
    <p>Malfunzionamento selezionato: <span><?= $this->malf; ?></span></p>
</div>
<div class="tab">
    <div class="tab-element rightBorder" style="width: 200px; float: left; height: 50px; text-align: center">Id</div>
    <div class="tab-element rightBorder" style="width: 200px; float: left; height: 50px; text-align: center">Nome</div>
    <div class="tab-element " style="width: 400px; float: left; height: 50px; text-align: center">Azione</div>
</div>
<? if($this->results != null): ?>
<? foreach($this->results as $item): ?>
    <a href="<?= $this->url(array(
        "controller" => "tecnico",
        "action" 	=>  "searchproducts",
        "id" => $item['id_componente']
    ),
        "default", true)?>" class="tab noRound">
        <div class="tab-element rightBorder" style="width: 200px; float: left; height: 50px; text-align: center">
            <?= $item['id_componente']; ?>
        </div>
        <div class="tab-element rightBorder" style="width: 200px; float: left; height: 50px; text-align: center">
            <?= $item['nome']; ?>
        </div>
        <div class="tab-element " style="width: 400px; float: left; height: 50px; text-align: center">
            <i class="fa fa-search"></i> Prodotti associati
        </div>
    </a>
<? endforeach; ?>
<? endif; ?>
