<div class="fullscreen-img height500" style="background-image: url('<?= $this->baseUrl('/img/slider/002.jpg');?>')">
</div>
<section class="page">
    <h2>Chi siamo</h2>
    <h3>Forniamo supporto e assistenza ai nostri clienti</h3>
    <p>
        Ufficialmente siamo nati nel 2010 dopo una decennale esperienza nel campo dell'assistenza informatica, maturata collaborando con aziende importanti e seguendo una passione sempre viva per la tecnologia.
        Dopo tanto tempo passato a "curare" i computers dei nostri clienti abbiamo deciso di intraprendere questo nuovo modo i fare assistenza: RAGGIUNGERE IL CLIENTE DIRETTAMENTE A DOMICILIO senza aggiungere costi di chiamata o di uscita.
        <br /></p>
    <p>
        L'impresa INNOVA INFORMATICA di ANCONA gestisce questa idea di fornire assistenza computers a domicilio affiancandola all'attività di CONSULENZA INFORMATICA
        <br />Uno staff di tecnici dislocati nel territorio di ANCONA e zone limitrofe sarà a tua completa disposizione risolvendo i tuoi problemi con velocità e competenza.
        Chiamaci per fissare un appuntamento.
    </p>
    </section>
