<div class="fullscreen-img height500" style="background-image: url('<?= $this->baseUrl('/img/slider/003.jpg');?>')">
</div>
<section class="page">
    <h2>Le nostre attività</h2>
    <h3>Consulenza</h3>
    <p>
        Perchè spendere tanti soldi.... quando risparmiando puoi avere di più?
        E' ormai fondamentale avere, all'interno di un'impresa, una figura di fiducia con competenze informatiche a 360 gradi.
        Per questo tutte le aziende stanno prendendo accordi con professionisti "esterni" in grado di risolvere tutte le problematiche informatiche, con lo scopo di migliorare la produttività e ridurre i costi.
        Vi offriamo una persona di fiducia su cui contare, un esperto sempre aggiornato, una persona motivata e innamorata del proprio lavoro, un risparmio sui costi informatici e un miglioramento della vostra azienda.
        Contattaci per un colloquio.
    </p>
</section>