<div class="row">
    <h2>TechDesk</h2>
    <p>P.IVA 000000000000000</p>
    <p><i class="fa fa-location-arrow"></i> Via brecce bianche, Ancona, IT</p>
    <p><i class="fa fa-mobile"></i> +39 081 88 88 888</p>
    <p><i class="fa fa-envelope-o"></i><a href="mailto:mail@mail.com">mail@mail.com</a></p>
</div>
<div class="row">
    <a href="../docs/relazione.pdf" target="_blank"><h3><i class="fa fa-download"></i> Progetto Tecnologie Web - UNIVPM</h3></a>
    <a href="../docs/mappa.pdf" target="_blank"><h3><i class="fa fa-institution"></i> Mappa dei link</h3></a>
</div>