<div class="menu-box">
    <ul class="list">
        <li class="item"><a href="<?php echo $this->url(array(
                'controller' => 'catalogo',
                'action' 	=>  'productlist',
            ),
                'default', true);?>" class=""><i class="fa fa-list"></i>Lista prodotti</a></li>
        <li class="item"><a href="<?php echo $this->url(array(
                'controller' => 'catalogo',
                'action' 	=>  'malfunzionamentilist',
            ),
                'default', true);?>" class=""><i class="fa fa-list"></i>Lista malfunzionamenti</a></li>
    </ul>
</div>