<!--FINESTRA ALERT-->
<div id="modal-box" class="whiteBg">
<!--    <div class="back"><a href="--><?php //echo $this->url(array(
//            'controller' => 'catalogo',
//            'action' 	=>  'malfunzionamentilist',
//        ),
//            'default', true);?><!--" class="">Annulla inserimento</a> </div>-->
    <div id="modal-alert" class="crud">
        <h2>Inserisci un nuovo malfunzionamento</h2>
        <?= $this->createFormM; ?>
        <h3 class="msg"></h3>
    </div>
</div>


