<div class="title-page">
    <h2>Gestisci associazione malfunzionamento prodotto/componente</h2>
</div>

<div id="ass-content">

<h2><a href="<?php echo $this->url(array(
        'controller' => 'malfunzionamento',
        'action' 	=>  'listaprodotti',
    ),
        'default', true);?>">Malfunzionamento-Prodotto</a></h2>
<h2><a href="<?php echo $this->url(array(
        'controller' => 'malfunzionamento',
        'action' 	=>  'listacomponenti',
    ),
        'default', true);?>">Malfunzionamento-Componente</a></h2>

</div>

