<? $role=Zend_Auth::getInstance() -> getIdentity()->role; ?>

<div class="title-page">
    <h2><?= $this->msg; ?></h2>
    <p>Prodotto selezionato: <span><?= $this->item['nome']; ?></span></p>
</div>

<div class="tab">
    <div class="tab-element rightBorder" style="width: 200px; float: left; height: 50px; text-align: center">Id</div>
    <div class="tab-element rightBorder" style="width: 200px; float: left; height: 50px; text-align: center">Immagine</div>
    <div class="tab-element rightBorder" style="width: 200px; float: left; height: 50px; text-align: center">Nome</div>
    <div class="tab-element" style="width: 200px; float: left; height: 50px; text-align: center">Descrizione</div>
</div>
    <a href="#" class="tab noRound">
        <div class="tab-element rightBorder" style="width: 200px; float: left; height: 50px; text-align: center">
            <?= $this->item['id_prodotto']; ?>
        </div>
        <div class="tab-element rightBorder" style="width: 200px; float: left; height: 50px; text-align: center">
            <img src="/public/import/<?= $this->item['img_path'];?>" height="30" class="marginTop10" />
        </div>
        <div class="tab-element rightBorder" style="width: 200px; float: left; height: 50px; text-align: center">
            <?= $this->item['nome']; ?>
        </div>
        <div class="tab-element " style="width: 200px; float: left; height: 50px; text-align: center">
            <?= $this->item['desc_prod']; ?>
        </div>
    </a>
    <div class="row-label">
        <p>Componenti</p>
    </div>
<div class="tab noMarginTop">
    <div class="tab-element rightBorder" style="width: 200px; float: left; height: 50px; text-align: center">Id</div>
    <div class="tab-element rightBorder" style="width: 200px; float: left; height: 50px; text-align: center">Nome</div>
    <div class="tab-element " style="width: 400px; float: left; height: 50px; text-align: center">Azione</div>
</div>
<? foreach($this->componenti as $comp): ?>
<a href="<?= $this->url(array(
    "controller" => "malfunzionamenti",
    "action" 	=>  "componentdetail",
    "id" => $comp['id_componente']
),
    "default", true)?>" class="tab noRound">
    <div class="tab-element rightBorder" style="width: 200px; float: left; height: 50px; text-align: center">
        <?= $comp['id_componente']; ?>
    </div>
    <div class="tab-element rightBorder" style="width: 200px; float: left; height: 50px; text-align: center">
        <?= $comp['nome']; ?>
    </div>
    <div class="tab-element " style="width: 400px; float: left; height: 50px; text-align: center">
        <i class="fa fa-pencil-square-o"></i>
    </div>
</a>
<? endforeach; ?>




<!--    <ul class="component-list">-->
<!--        --><?// foreach($this->componenti as $comp): ?>
<!--            <li class="component-list-item"><a href="--><?//= $this->url(array(
//                    "controller" => "malfunzionamenti",
//                    "action" 	=>  "componentdetail",
//                    "id" => $comp['id_componente']
//                ),
//                    "default", true)?><!--">--><?//= $comp['nome']; ?><!--</a></li>-->
<!--        --><?// endforeach; ?>
<!--    </ul>-->
    <div class="row-label">
        <p>Malfunzionamenti prodotto</p>
    </div>
    <? if($role=='tecnico'): ?>


        <ul class="component-list">
            <? foreach ($this->malf_prod as $k): ?>
                <li class="component-list-item"><a class="ajaxmalf" value="<?= $k['id_malfunzionamento']; ?>" href="#">
                        <?= $k['nome']; ?></a></li>
            <? endforeach; ?>
        </ul>
    <? elseif($role=='staff'): ?>
        <div class="tab noMarginTop">
            <div class="tab-element rightBorder" style="width: 200px; float: left; height: 50px; text-align: center">Id</div>
            <div class="tab-element rightBorder" style="width: 200px; float: left; height: 50px; text-align: center">Nome</div>
            <div class="tab-element " style="width: 400px; float: left; height: 50px; text-align: center">Azione</div>
        </div>
        <? foreach($this->malf_prod as $item): ?>
            <a href="<?= $this->url(array(
                "controller" => "malfunzionamenti",
                "action" 	=>  "searchproducts",
                "id" => $item['id_malfunzionamento']
            ),
                "default", true)?>" class="tab noRound">
                <div class="tab-element rightBorder" style="width: 200px; float: left; height: 50px; text-align: center">
                    <?= $item['id_malfunzionamento']; ?>
                </div>
                <div class="tab-element rightBorder" style="width: 200px; float: left; height: 50px; text-align: center">
                    <?= $item['nome']; ?>
                </div>
                <div class="tab-element " style="width: 400px; float: left; height: 50px; text-align: center">
                    <i class="fa fa-pencil-square-o"></i>
                </div>
            </a>
        <? endforeach; ?>
    <? endif ?>

<div class="popup-bg ajax hidden">
    <div class="popup">
        <i class="fa fa-times ajax"></i>
        <div class="product-box">
            <div class="product-component">
                <p><span>Nome malfunzionamento:</span><span class="space name">test</span></p>
                <p><span>Descrizione malfunzionamento:</span><span class="space desc">test</span></p>
                <p><span>Soluzione: </span></p>
            </div>
            <div class="product-component solution-text">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
        </div>
    </div>
</div>

<script>
    $("a.ajaxmalf").unbind("click").click(function(e){
        var el=$(this);
        var id=el.attr("value");
        var url="<?= $this->baseUrl('/malfunzionamenti/findsolution'); ?>";
        e.preventDefault();
        ajaxdetails(id,url);
        console.log("a");
    });

    $("i.fa-times.ajax").click(function(){
        popupInit();
    });
</script>