<div class="title-page">
    <h2><?= $this->msg; ?></h2>
    <p>Parola ricercata: <span><?= $this->word; ?></span></p>
</div>
<div class="tab">
    <div class="tab-element rightBorder" style="width: 200px; float: left; height: 50px; text-align: center">Id</div>
    <div class="tab-element rightBorder" style="width: 200px; float: left; height: 50px; text-align: center">Nome</div>
    <div class="tab-element " style="width: 400px; float: left; height: 50px; text-align: center">Azione</div>
</div>

<? if($this->flag): ?>
<? foreach($this->results as $item): ?>
    <a href="<?= $this->url(array(
        "controller" => "malfunzionamenti",
        "action" 	=>  "searchcomponents",
        "id" => $item['id_malfunzionamento']
    ),
        "default", true)?>" class="tab noRound">
        <div class="tab-element rightBorder" style="width: 200px; float: left; height: 50px; text-align: center">
            <?= $item['id_malfunzionamento']; ?>
        </div>
        <div class="tab-element rightBorder" style="width: 200px; float: left; height: 50px; text-align: center">
            <?= $item['nome']; ?>
        </div>
        <div class="tab-element " style="width: 400px; float: left; height: 50px; text-align: center">
            <i class="fa fa-search"></i> Componenti associate
        </div>
    </a>
<? endforeach; ?>

<? else: ?>
    <? foreach($this->results as $item): ?>
        <a href="<?= $this->url(array(
            "controller" => "malfunzionamenti",
            "action" 	=>  "itemdetail",
            "id" => $item['id_prodotto']
        ),
            "default", true)?>" class="tab noRound">
            <div class="tab-element rightBorder" style="width: 200px; float: left; height: 50px; text-align: center">
                <?= $item['id_prodotto']; ?>
            </div>
            <div class="tab-element rightBorder" style="width: 200px; float: left; height: 50px; text-align: center">
                <?= $item['nome']; ?>
            </div>
            <div class="tab-element " style="width: 400px; float: left; height: 50px; text-align: center">
                <i class="fa fa-search"></i> Scheda prodotto
            </div>
        </a>
    <? endforeach; ?>
<? endif ?>
