<? $role= Zend_Auth::getInstance()->getIdentity()->role; ?>

<div class="title-page">
    <h2><?= $this->msg; ?></h2>
</div>
<div style="width: 800px; margin: auto">
    <div class="tab topRow">
        <div class="tab-element rightBorder" style="width: 200px; float: left; height: 50px; text-align: center">Id</div>
        <div class="tab-element rightBorder" style="width: 200px; float: left; height: 50px; text-align: center">Nome</div>
        <div class="tab-element rightBorder" style="width: 200px; float: left; height: 50px; text-align: center">Descrizione</div>
        <div class="tab-element" style="width: 200px; float: left; height: 50px; text-align: center">Azione</div>

    </div>
    <? if($this->products!=null): ?>
    <? foreach($this->products as $item): ?>
        <a href="#" class="tab noRound admin-product-assoc" value="<?= $item['id_prodotto']; ?>" style="height: 350px">
            <div class="tab-element rightBorder" style="width: 200px; float: left; height: 350px; text-align: center">
                <?= $item['id_prodotto']; ?>
            </div>
            <div class="tab-element rightBorder" style="width: 200px; float: left; height: 350px; text-align: center">
                <?= $item['nome']; ?>
            </div>
            <div class="tab-element rightBorder nome" style="width: 200px; float: left; height: 350px; text-align: center">
                <p class="faq-text"><?= $item['desc_prod']; ?></p>
            </div>
            <div class="tab-element" style="width: 200px; float: left; height: 350px; text-align: center">
                <i class="fa fa-exchange"></i>
            </div>
        </a>
    <? endforeach; ?>
    <? else: ?>
        <h2>Non sono presenti prodotti nel db</h2>
    <? endif; ?>
</div>


<div id="modal-change-box">
    <i class="fa fa-times"></i>
    <div id="modal-change-box-content">
        <? if($role=='tecnico'): ?>
            <h2>Componenti disponibili</h2>
        <? elseif($role=='staff' || $role=='admin'): ?>
            <h2>Modifica associazione prodotto-componente</h2>
        <? endif ?>
        <h3>Seleziona il nome della componente per accedere alla sua descrizione</h3>
        <p>Prodotto selezionato selezionato: <span>test</span></p>
        <h3>Clicca sul componente per creare o rimuovere l'associazione</h3>
        <h2>Componenti</h2>
        <div class="solutions-list">
        </div>
        <? if($role=='staff' || $role=='admin'): ?>
            <p class="correct-insert"></p>
            <p class="wrong-insert"></p>
        <? endif ?>
    </div>
    <div id="modal-change-box-description">
        <h2>Descrizione componente</h2>
        <p></p>
    </div>
</div>