<div class="title-page">
    <h2><?= $this->msg; ?></h2>
</div>
<div style="width: 800px; margin: auto">
    <div class="tab topRow">
        <div class="tab-element rightBorder" style="width: 200px; float: left; height: 50px; text-align: center">Id</div>
        <div class="tab-element rightBorder" style="width: 200px; float: left; height: 50px; text-align: center">Nome</div>
        <div class="tab-element rightBorder" style="width: 200px; float: left; height: 50px; text-align: center">Descrizione</div>

        <div class="tab-element rightBorder" style="width: 100px; float: left; height: 50px; text-align: center">Modifica</div>
        <div class="tab-element " style="width: 100px; float: left; height: 50px; text-align: center">Elimina</div>

    </div>
    <? foreach($this->products as $item): ?>
        <a href="#" class="tab noRound admin-product" value="<?= $item['id_prodotto']; ?>" style="height: 350px">
            <div class="tab-element rightBorder" style="width: 200px; float: left; height: 350px; text-align: center">
                <?= $item['id_prodotto']; ?>
            </div>
            <div class="tab-element rightBorder" style="width: 200px; float: left; height: 350px; text-align: center">
                <?= $item['nome']; ?>
            </div>
            <div class="tab-element rightBorder" style="width: 200px;float:left; height:350px; text-align: center">
                <p class="faq-text"><?= $item['desc_prod']; ?></p>
            </div>
            <div class="tab-element rightBorder" style="width: 100px; float: left; height: 350px; text-align: center">
                <i class="fa fa-pencil"></i>
            </div>
            <div class="tab-element " style="width: 100px; float: left; height: 350px; text-align: center">
                <i class="fa fa-trash"></i>
            </div>
        </a>
    <? endforeach; ?>
</div>